spring.application.name=gokapp
server.servlet.session.timeout=8h

# Default profile = dev
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# --- Thymeleaf (optional tweaks) ---
spring.thymeleaf.cache=false